-- MGBOARD 삽입
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글1', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글2', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글3', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글4', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글5', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글6', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글7', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글8', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글9', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글10', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글12', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글13', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글14', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글15', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글16', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글17', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD M VALUES (MGB_SEQ_IDX.NEXTVAL, 'ㅇㅇ', '1234' , '자유게시판 글18', '<P><IMG SRC="HTTPS://PICSUM.PHOTOS/250/250" STYLE="WIDTH: 250PX;"></P><P>ㅇㅇ</P>', SYSDATE ,0, '0:0:0:0:0:0:0:1');

-- MGM
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런1', '1234', '수원 맛집이에요1' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-15.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런3', '1234', '수원 맛집이에요3' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-13.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런4', '1234', '수원 맛집이에요4' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-18.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런5', '1234', '수원 맛집이에요5' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-13.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런6', '1234', '수원 맛집이에요6' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-13.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런7', '1234', '수원 맛집이에요7' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-13.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런8', '1234', '수원 맛집이에요8' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-13.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런9', '1234', '수원 맛집이에요9' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런10', '1234', '수원 맛집이에요10' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런11', '1234', '수원 맛집이에요11' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런12', '1234', '수원 맛집이에요12' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런13', '1234', '수원 맛집이에요13' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런14', '1234', '수원 맛집이에요14' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런15', '1234', '수원 맛집이에요15' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런16', '1234', '수원 맛집이에요16' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런17', '1234', '수원 맛집이에요17' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런18', '1234', '수원 맛집이에요18' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="HTTPS://GENERATORFUN.COM/CODE/UPLOADS/RANDOM-FOOD-IMAGE-11.JPG" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );

-- MGH
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런1', '1234', '수원시에서 대란이에요1' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런2', '1234', '수원시에서 대란이에요2' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런3', '1234', '수원시에서 대란이에요3' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런4', '1234', '수원시에서 대란이에요4' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런5', '1234', '수원시에서 대란이에요5' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런6', '1234', '수원시에서 대란이에요6' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런7', '1234', '수원시에서 대란이에요7' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런8', '1234', '수원시에서 대란이에요8' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런9', '1234', '수원시에서 대란이에요9' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런10', '1234', '수원시에서 대란이에요10' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런11', '1234', '수원시에서 대란이에요11' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런12', '1234', '수원시에서 대란이에요12' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD M2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런13', '1234', '수원시에서 대란이에요13' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 거래 지역을 작성해 주세요. <BR> - 거래 지역(구/동 단위) : ─────────────</P><P><IFRAME FRAMEBORDER="0" SRC="//WWW.YOUTUBE.COM/EMBED/73MYYIF4BFQ" WIDTH="640" HEIGHT="360" CLASS="NOTE-VIDEO-CLIP"></IFRAME><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;"><BR></SPAN></P><P><SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</SPAN><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );

-- MGA
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감2' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감3' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감4' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감5' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감6' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감7' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감8' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감9' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감10' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감11' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD M VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'GGPW', '수원 알바구함 선착순 마감12' , '<P></P><H2>정보</H2><HR><H5><I CLASS="BI BI-CASH-COIN"></I> 시급 : 1만원</H5><BR><H5><I CLASS="BI BI-CALENDAR"></I> 요일 : 월화수목금</H5><BR><H5><I CLASS="BI BI-CLOCK"></I> 시간 : 9시간&NBSP;</H5><BR>
<H5><I CLASS="BI BI-PHONE"></I> 연락처 : 01022223333</H5><BR><BR><H2>상세 내용</H2><HR><P></P><P>매장관리 알바 구합니다.</P><P>미성년자 안되요!~</P><P>평일 야간 근무 가능하신분~</P><P><BR></P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );

-- MGU
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@1' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@2' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@3' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@4' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@5' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@6' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@7' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@8' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@9' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@10' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@11' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@12' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@13' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD M2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'GGPW', '책상 빌런이 책상 2만원에 넘겨요@14' , '<P><IMG SRC="HTTPS://I.NAMU.WIKI/I/U8QV8L2KWXCT7K_M5VT2C_I_-O6UWVK470GWEC4GCARM2KKRZ5VV6SPYLGG82Y2V6HVBLIASNSGK5SF6Q7P3IQ.WEBP" STYLE="WIDTH: 360PX;"></P><P>책상 팔아요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
