-- mgboard 삽입
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글1', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글2', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글3', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글4', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글5', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글6', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글7', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글8', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글9', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글10', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글12', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글13', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글14', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글15', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글16', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글17', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');
INSERT INTO MGBOARD m values (mgb_seq_idx.nextval, 'ㅇㅇ', '1234' , '자유게시판 글18', '<p><img src="https://picsum.photos/250/250" style="width: 250px;"></p><p>ㅇㅇ</p>', sysdate ,0, '0:0:0:0:0:0:0:1');

-- mgm
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런1', '1234', '수원 맛집이에요1' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-15.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런3', '1234', '수원 맛집이에요3' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-13.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런4', '1234', '수원 맛집이에요4' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-18.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런5', '1234', '수원 맛집이에요5' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-13.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런6', '1234', '수원 맛집이에요6' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-13.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런7', '1234', '수원 맛집이에요7' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-13.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런8', '1234', '수원 맛집이에요8' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-13.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런9', '1234', '수원 맛집이에요9' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런10', '1234', '수원 맛집이에요10' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런11', '1234', '수원 맛집이에요11' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런12', '1234', '수원 맛집이에요12' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런13', '1234', '수원 맛집이에요13' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런14', '1234', '수원 맛집이에요14' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런15', '1234', '수원 맛집이에요15' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런16', '1234', '수원 맛집이에요16' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런17', '1234', '수원 맛집이에요17' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );
INSERT INTO MGMBOARD M VALUES (MGM_SEQ_IDX.NEXTVAL, '블루베리맛집빌런18', '1234', '수원 맛집이에요18' , '<P>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <BR> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <BR> ▼ 맛집 위치를 작성해 주세요. <BR> - 지역(구/동 단위) : ───────────<SPAN STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM;">────────</SPAN><IMG SRC="https://generatorfun.com/code/uploads/Random-Food-image-11.jpg" STYLE="FONT-FAMILY: VAR(--BS-FONT-SANS-SERIF); FONT-SIZE: 1REM; WIDTH: 640PX;"></P><P>블루베리 맛집이에요</P>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '블루베리 맛집이에요' );

-- mgh
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런1', '1234', '수원시에서 대란이에요1' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런2', '1234', '수원시에서 대란이에요2' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런3', '1234', '수원시에서 대란이에요3' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런4', '1234', '수원시에서 대란이에요4' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런5', '1234', '수원시에서 대란이에요5' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런6', '1234', '수원시에서 대란이에요6' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런7', '1234', '수원시에서 대란이에요7' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런8', '1234', '수원시에서 대란이에요8' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런9', '1234', '수원시에서 대란이에요9' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런10', '1234', '수원시에서 대란이에요10' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런11', '1234', '수원시에서 대란이에요11' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런12', '1234', '수원시에서 대란이에요12' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );
INSERT INTO MGHBOARD m2 VALUES (MGH_SEQ_IDX.NEXTVAL, '핫딜빌런13', '1234', '수원시에서 대란이에요13' , '<p>※ 유튜브, 블로그, 인스타그램 등 상품 정보 제공 목적 링크 가능(외부 거래를 유도하는 링크 제외) <br> ※ 등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 중고나라 사기통합조회 DB로 수집/활용될 수 있습니다. <br> ▼ 거래 지역을 작성해 주세요. <br> - 거래 지역(구/동 단위) : ─────────────</p><p><iframe frameborder="0" src="//www.youtube.com/embed/73MYYif4BFQ" width="640" height="360" class="note-video-clip"></iframe><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;"><br></span></p><p><span style="font-family: var(--bs-font-sans-serif); font-size: 1rem;">롯데마트 맥주 6캔에 1만원@@@@@@@@@@@@@@@@@@@@@@@@</span><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 영통구 봉영로 1579', '핫딜빌런추천이에요' );

-- mga
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감2' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감3' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감4' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감5' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감6' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감7' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감8' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감9' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감10' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감11' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );
INSERT INTO MGABOARD m VALUES (MGA_SEQ_IDX.NEXTVAL, 42, 'ggpw', '수원 알바구함 선착순 마감12' , '<p></p><h2>정보</h2><hr><h5><i class="bi bi-cash-coin"></i> 시급 : 1만원</h5><br><h5><i class="bi bi-calendar"></i> 요일 : 월화수목금</h5><br><h5><i class="bi bi-clock"></i> 시간 : 9시간&nbsp;</h5><br>
<h5><i class="bi bi-phone"></i> 연락처 : 01022223333</h5><br><br><h2>상세 내용</h2><hr><p></p><p>매장관리 알바 구합니다.</p><p>미성년자 안되요!~</p><p>평일 야간 근무 가능하신분~</p><p><br></p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', 'GC26 1층' );

-- MGU
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@1' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@2' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@3' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@4' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@5' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@6' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@7' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@8' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@9' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@10' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@11' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@12' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@13' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
INSERT INTO MGUBOARD m2 VALUES (MGU_SEQ_IDX.NEXTVAL, 42, 'ggpw', '책상 빌런이 책상 2만원에 넘겨요@14' , '<p><img src="https://i.namu.wiki/i/u8Qv8l2kwXCT7K_M5Vt2c_i_-O6UwVK470gwec4GcarM2KKRz5vV6SPylgG82Y2V6hvbLIaSnSGk5SF6Q7P3IQ.webp" style="width: 360px;"></p><p>책상 팔아요</p>', SYSDATE , 0 , '255.255.255.06', '경기 수원시 권선구 경수대로 88', '책상빌런',12 );
